# .goreleaser.yml
builds:
  - binary: aws-ssh
    goos:
      - darwin
      - linux
    goarch:
      - amd64
nfpms:
  - vendor: Springload
    homepage: https://springload.co.nz

    maintainer: DevOps team
    description: Traverses through all available AWS accounts to generate ssh config
    license: Apache 2.0
    formats:
      - deb
      - rpm

brews:
  - name: aws-ssh
    github:
      owner: springload
      name: homebrew-tools
    folder: Formula

snapcrafts:
  - name: springload-aws-ssh
    publish: true
    summary: Traverses through all AWS in parallel to construct ssh config
    description: This utility traverses through all AWS in parallel to construct ssh config. It does all profiles in parallel, so it's pretty fast.
    grade: stable
    apps:
      aws-ssh:
        plugs: ["home","networks"]

