# .goreleaser.yml
builds:
  - binary: aws-ssh
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
nfpms:
  - vendor: Springload
    homepage: https://springload.co.nz

    maintainer: DevOps team
    description: Traverses through all available AWS accounts to generate ssh config
    license: Apache 2.0
    formats:
      - deb
      - rpm

brews:
  - name: aws-ssh
    tap:
      owner: springload
      name: homebrew-tools
    folder: Formula
